from .ford.fiesta import Fiesta
from .ford.kuga import Kuga
from .ford.mustang import Mustang
from .mercedes.classa import ClassA
from .mercedes.glc import Glc
from .mercedes.amgcoupe import AmgCoupe
from .toyota.aygo import Aygo
from .toyota.rav4 import Rav4
from .toyota.supra import Supra